---
- name: Update APT Package Cache
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_pkg_mgr == 'apt'

- name: Update YUM Package Cache
  ansible.builtin.dnf:
    update_cache: yes
  when: ansible_pkg_mgr == 'yum'

- name: Install Prerequisites
  ansible.builtin.package:
    name:
      - mariadb-server
      - mariadb-client
    state: latest

- name: Start MariaDB Service
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: yes
