OS:
  Linux-Support:
    - Ubuntu 18.04
    - Ubuntu 20.04
    - Ubuntu 21.04
    - Debian 9
    - Debian 10
    - Debian 11
    - Kali Linux
    - CentOS 7
    - CentOS 8
    - Fedora 34
    - Fedora 35
    - Arch Linux
  Windows-Support:
    - Windows 10
    - Windows Server 2012
    - Windows Server 2016
    - Windows Server 2019
    - Windows Server 2022
