---
- name: Include Variables
  ansible.builtin.include_vars:
    file: default.yaml

- name: Update APT Package Cache
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_pkg_mgr == 'apt'

- name: Update YUM Package Cache
  ansible.builtin.dnf:
    update_cache: yes
  when: ansible_pkg_mgr == 'yum'

- name: Install MariaDB
  ansible.builtin.package:
    name:
      - mariadb-server
      - mariadb-client
      - python3-pymysql
    state: present

- name: Copy my.cnf
  ansible.builtin.template:
    src: my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600

- name: Copy 50-server.cnf
  ansible.builtin.copy:
    src: 50-server.cnf
    dest: /etc/mysql/mariadb.conf.d/50-server.cnf
    owner: root
    group: root
    mode: 0644

- name: Start MariaDB
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: yes

# MySQL Configuration

- name: Set the root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Creates database for WordPress
  mysql_db:
    name: "{{ mysql_db }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Create MySQL user for WordPress
  mysql_user:
    name: "{{ mysql_user }}"
    host: "%"
    password: "{{ mysql_password }}"
    priv: "{{ mysql_db }}.*:ALL"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
