name = "wordpress-web"
type = "http"
port = 80
protocol = "tcp"
limit = 5
user = "root"
supportedos = [ "ubuntu", "debian" ]

[http]
host = "evandeters.com"
RequireDB = true


[dependency]
service = ["wordpress-db"]

