name = "wordpress-web"
type = "http"
port = 80
protocol = "tcp"
limit = 5
user = "root"
supportedos = [ "ubuntu", "debian" ]
dependency = ["wordpress-db"]

[http]
host = "evandeters.com"
RequireDB = true
VarTmplPath = "vars/default.tmpl"
VarYamlPath = "vars/default.yaml"
